scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:

  # Reports when you use improper spacing around ! in !default, !global,
  # !important, and !optional flags.
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  # Reports when a BEM selector contains more elements than
  # a configurable maximum number.
  BemDepth:
    enabled: false
    max_elements: 1

  # "border: 0" not "border: none"
  BorderZero:
    enabled: true
    convention: zero

 # No capitals in selectors
  CapitalizationInSelector:
    enabled: true

  ChainedClasses:
    enabled: false

  # "#0f0" not "green"
  ColorKeyword:
    enabled: true

  # Prefer color literals (keywords or hexadecimal codes) to be used
  # only in variable declarations.
  # They should be referred to via variables everywhere else.
  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    style: silent

  # Disallow "@debug"
  DebugStatement:
    enabled: true

  # @extend must come first, then properties, then nested rulesets
  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  # Disallow use of the same property more than once in the same ruleset
  DuplicateProperty:
    enabled: true

  # Place @else statements on the same line as the preceding curly brace.
  ElsePlacement:
    enabled: true
    style: same_line

  # Require an empty line between rulesets
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  # Disallow empty rulesets
  EmptyRule:
    enabled: true

  # Reports when you have an @extend directive.
  ExtendDirective:
    enabled: false

  # Require a newline at the end of the file
  FinalNewline:
    enabled: true
    present: true

  # #12346 good, #123 bad.
  HexLength:
    enabled: true
    style: long

  # Require hex colors to be lowercase (if they include any of the letters a-f)
  HexNotation:
    enabled: true
    style: lowercase

  # Hex colors must be actual colors (ie not #ab or #00mm00)
  HexValidation:
    enabled: true

  # Avoid using ID selectors.
  IdSelector:
    enabled: true

  # Avoid using !important in properties.
  ImportantRule:
    enabled: true

  # The basenames of @imported SCSS partials should not begin with
  # an underscore and should not include the filename extension.
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  # Use two spaces per indentation level.
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  # 0.1 not .1
  LeadingZero:
    enabled: true
    style: include_zero

  # Reports when you define the same selector twice in a single sheet.
  MergeableSelector:
    enabled: true
    force_nesting: true

  # Functions, mixins, variables, and placeholders should be declared with all
  # lowercase letters and hyphens instead of underscores.
  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase

  # Avoid nesting selectors too deeply.
  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  # Always use placeholder selectors in @extend.
  PlaceholderInExtend:
    enabled: true

  # Limit the number of properties in a rule set.
  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  # Sort properties in a strict order
  # List of SMACSS sort order can be found here:
  # https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/smacss.txt
  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order: smacss

  # Reports when you use an unknown or disabled CSS property
  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []

  # Configure which units are allowed for property values.
  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  # Pseudo-elements, like ::before, and ::first-letter, should be declared
  # with two colons.
  PseudoElement:
    enabled: true

  # Avoid qualifying elements in selectors (also known as "tag-qualifying").
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  # Don't write selectors with a depth of applicability greater than 3.
  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  # Prefer the shortest shorthand form possible for properties that support it.
  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]

  # Properties within rule sets should each reside on their own line.
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  # Split selectors onto separate lines after each comma, and have each
  # individual selector occupy a single line.
  SingleLinePerSelector:
    enabled: true

  # Commas in lists should be followed by a space.
  SpaceAfterComma:
    enabled: true
    style: one_space

  # Properties should be formatted with a single space separating the colon
  # from the property's value.
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  # Properties should be formatted with no space between the name and the colon.
  SpaceAfterPropertyName:
    enabled: true

  # Variables should be formatted with no space between the name and the colon.
  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  # Property values; @extend, @include, and @import directives; and variable
  # declarations should always end with a semicolon.
  TrailingSemicolon:
    enabled: true

  # Reports lines containing trailing whitespace.
  TrailingWhitespace:
    enabled: true

  # Don't write trailing zeros for numeric values with a decimal point.
  TrailingZero:
    enabled: false

  # Don't use the all keyword to specify transition properties.
  TransitionAll:
    enabled: false

  # Numeric values should not contain unnecessary fractional portions.
  UnnecessaryMantissa:
    enabled: true

  # Do not use parent selector references (&) when they would
  # otherwise be unnecessary.
  UnnecessaryParentReference:
    enabled: true

  # URLs should not contain protocols or domain names.
  UrlFormat:
    enabled: true

  # URLs should always be enclosed within quotes.
  UrlQuotes:
    enabled: true

  # Properties, like color and font, are easier to read and maintain when
  # defined using variables rather than literals.
  VariableForProperty:
    enabled: false
    properties: []

  # Avoid vendor prefixes.
  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  # Omit length units on zero values.
  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
